export const posts = [
  {
    id: 1,
    title: 'A detailed step by step guide to manage your lifestyle',
    excerpt: 'A Simple Step-by-Step Guide to Managing Your Lifestyle',
    slug: 'a-detailed-step-by-step-guide-to-manage-your-lifestyle',
    content: "<h1>A Simple Step-by-Step Guide to Managing Your Lifestyle</h1><p>Managing your lifestyle effectively can lead to improved well-being and happiness. Here’s a straightforward guide to help you take control of your life:</p><h2>1. <strong>Set Clear Goals</strong></h2><p>Identify what you want to achieve in different areas of your life, such as health, career, relationships, and personal growth.</p><h2>2. <strong>Create a Routine</strong></h2><p>Establish daily habits that align with your goals. Consistency is key to making lasting changes.</p><h2>3. <strong>Prioritize Self-Care</strong></h2><p>Make time for activities that rejuvenate you, whether it’s exercise, meditation, or hobbies you love.</p><h2>4. <strong>Stay Organized</strong></h2><p>Use planners or digital tools to keep track of your tasks and appointments. This helps reduce stress and increases productivity.</p><h2>5. <strong>Maintain a Balanced Diet</strong></h2><p>Fuel your body with nutritious foods that provide energy and support overall health.</p><h2>6. <strong>Get Regular Exercise</strong></h2><p>Incorporate physical activity into your routine to boost mood and improve physical health.</p><h2>7. <strong>Connect with Others</strong></h2><p>Nurture relationships with friends and family for emotional support and social fulfillment.</p><h2>8. <strong>Reflect and Adjust</strong></h2><p>Regularly assess your progress towards your goals and make adjustments as needed.</p><p>By following these steps, you can create a lifestyle that supports your well-being and helps you achieve your aspirations.</p>",
    category: 'Lifestyle',
    categoryId: 3,
    authorId: '1afa5662-132d-48d2-8768-9543a4a96501',
    readingTime: 10,
    image: 'https://picsum.photos/1200/700?random=1',
    isFeatured: true,
    isPublished: false,
  },
  {
    id: 3,
    title: 'Learning new technology to boost your career in software',
    excerpt: 'Learning New Tech to Boost Your Software Career',
    authorId: '1afa5662-132d-48d2-8768-9543a4a96501',
    readingTime: 6,
    slug: 'learning-new-technology-to-boost-your-career-in-software',
    content: "<h1>Learning New Tech to Boost Your Software Career</h1><p>In tech, staying still means falling behind. Here's how learning new technologies can fast-track your software career:</p><h2>1. <strong>Stay Relevant</strong></h2><p>Tech evolves fast. Learning modern tools, frameworks, or languages keeps you valuable to employers and clients.</p><h2>2. <strong>Increase Opportunities</strong></h2><p>New skills open doors—whether it's switching to a better role, freelancing, or launching your own product.</p><h2>3. <strong>Grow Your Confidence</strong></h2><p>Tackling new tech boosts problem-solving skills and helps you adapt quickly in real-world projects.</p><h2>4. <strong>Stand Out</strong></h2><p>Knowing in-demand skills (like TypeScript, DevOps, AI/ML, or cloud platforms) makes your resume and GitHub shine.</p><h2>5. <strong>How to Learn Smart</strong></h2><ol><li data-list=\"bullet\"><span class=\"ql-ui\" contenteditable=\"false\"></span>Pick tech that aligns with your goals</li><li data-list=\"bullet\"><span class=\"ql-ui\" contenteditable=\"false\"></span>Build real projects</li><li data-list=\"bullet\"><span class=\"ql-ui\" contenteditable=\"false\"></span>Join communities and open source</li><li data-list=\"bullet\"><span class=\"ql-ui\" contenteditable=\"false\"></span>Stay consistent, not perfect</li></ol><p><br></p>",
    category: 'Technology',
    categoryId: 1,
    image: 'https://picsum.photos/1200/700?random=3',
    isFeatured: false,
    isPublished: true,
  },
  {
    id: 4,
    title: 'Tips for getting the most out of apps and software',
    excerpt: 'Tips for Getting the Most Out of Apps and Software',
    authorId: '1afa5662-132d-48d2-8768-9543a4a96501',
    readingTime: 7,
    slug: 'tips-for-getting-the-most-out-of-apps-and-software',
    content: "<h1>Tips for Getting the Most Out of Apps and Software</h1><p>We use tons of apps daily—but most people only scratch the surface. Here's how to truly unlock their value:</p><h2>1. <strong>Learn the Shortcuts</strong></h2><p>Keyboard shortcuts or gesture controls save time and improve your workflow.</p><h2>2. <strong>Explore All Features</strong></h2><p>Take time to go beyond the basics—many apps have hidden tools that boost productivity.</p><h2>3. <strong>Use Integrations</strong></h2><p>Connect apps (like linking your calendar with your task manager) to streamline your workflow.</p><h2>4. <strong>Customize Settings</strong></h2><p>Adjust preferences, themes, and notifications to suit how you work best.</p><h2>5. <strong>Keep It Updated</strong></h2><p>Updates often bring better features, security patches, and performance improvements.</p><h2>6. <strong>Sync Across Devices</strong></h2><p>Use cloud sync to stay productive whether you're on your phone, laptop, or tablet.</p><h2>7. <strong>Read the Docs or Tutorials</strong></h2><p>Official docs, videos, or help centers can reveal pro tips you might miss on your own.</p>",
    category: 'Technology',
    categoryId: 1,
    image: "https://picsum.photos/1200/700?random=4",
    isFeatured: false,
    isPublished: false,
  },
  {
    id: 5,
    title: 'Enhancing your skills and capturing memorable moments',
    excerpt: 'Enhancing Your Skills and Capturing Memorable Moments',
    slug: 'enhancing-your-skills-and-capturing-memorable-moments',
    authorId: '1afa5662-132d-48d2-8768-9543a4a96501',
    readingTime: 9,
    content: "<h1>Enhancing Your Skills and Capturing Memorable Moments</h1><p>In today’s fast-paced world, continuously improving your skills while cherishing life’s special moments is essential. Here’s how to strike that balance:</p><h2>1. <strong>Set Learning Goals</strong></h2><p>Identify specific skills you want to develop, whether professional or personal, and create a plan to achieve them.</p><h2>2. <strong>Practice Regularly</strong></h2><p>Consistency is key. Dedicate time each day or week to practice and refine your skills.</p><h2>3. <strong>Seek Feedback</strong></h2><p>Constructive criticism helps you grow. Don’t hesitate to ask mentors or peers for their insights.</p><h2>4. <strong>Document Your Journey</strong></h2><p>Keep a journal or blog to track your progress and reflect on your learning experiences.</p><h2>5. <strong>Capture Life’s Moments</strong></h2><p>Use photography or videography to document important events, travels, and everyday joys.</p><h2>6. <strong>Create a Memory Archive</strong></h2><p>Organize your photos and videos into albums or digital collections for easy access and reminiscing.</p><h2>7. <strong>Share Your Experiences</strong></h2><p>Sharing your skills and memories with others can inspire and connect you with like-minded individuals.</p><p>By focusing on skill enhancement while capturing life’s memorable moments, you can lead a fulfilling and enriched life.</p>",
    category: 'Lifestyle',
    categoryId: 5,
    image: "https://picsum.photos/1200/700?random=5",
    isFeatured: false,
    isPublished: true,
  },
  {
    id: 6,
    title: 'Maximizing returns by minimizing resources in your startup',
    excerpt: 'Maximizing Returns by Minimizing Resources in Your Startup',
    slug: 'maximizing-returns-by-minimizing-resources-in-your-startup',
    authorId: '1afa5662-132d-48d2-8768-9543a4a96501',
    readingTime: 8,
    content: "<h1>Maximizing Returns by Minimizing Resources in Your Startup</h1><p>Starting a business often means working with limited resources. However, with strategic planning and smart execution, you can maximize returns while minimizing resource expenditure. Here’s how:</p><h2>1. <strong>Focus on Core Competencies</strong></h2><p>Identify what your startup does best and concentrate your efforts there. Outsource non-core activities to save time and money.</p><h2>2. <strong>Leverage Technology</strong></h2><p>Utilize affordable or free tools and software to automate tasks, manage projects, and streamline operations.</p><h2>3. <strong>Adopt Lean Principles</strong></h2><p>Implement lean startup methodologies to test ideas quickly, gather feedback, and iterate without heavy upfront investments.</p><h2>4. <strong>Build Strategic Partnerships</strong></h2><p>Collaborate with other businesses to share resources, access new markets, and enhance your offerings.</p><h2>5. <strong>Optimize Marketing Efforts</strong></h2><p>Focus on cost-effective marketing strategies like social media, content marketing, and SEO to reach your target audience without breaking the bank.</p><h2>6. <strong>Monitor Financial Metrics</strong></h2><p>Keep a close eye on cash flow, expenses, and ROI to make informed decisions and avoid unnecessary spending.</p><h2>7. <strong>Cultivate a Resourceful Team</strong></h2><p>Hire versatile team members who can wear multiple hats and contribute to various aspects of the business.</p><p>By implementing these strategies, your startup can thrive by maximizing returns while efficiently utilizing available resources.</p>",
    category: 'Startup',
    categoryId: 2,
    image: "https://picsum.photos/1200/700?random=6",
    isFeatured: false,
    isPublished: true,
  },
  {
    id: 7,
    title: 'Taxes on Luxury Houses',
    slug: 'taxes-on-luxury-houses',
    category: 'Real Estate',
    authorId: '1afa5662-132d-48d2-8768-9543a4a96501',
    readingTime: 11,
    categoryId: 3,
    excerpt:
      'Luxury Home Taxes: Are They Fair, and What Do They Mean for the Market?',
    content: "<p>test</p>",
    category: 'Finance',
    categoryId: 1,
    image: "https://picsum.photos/1200/700?random=7",
    isFeatured: false,
    isPublished: true,
  },
  {
    id: 8,
    title: 'The New Way of Study',
    slug: 'the-new-way-of-study',
    authorId: '1afa5662-132d-48d2-8768-9543a4a96501',
    readingTime: 10,
    excerpt: 'The New Way of Study: Ditching the Old, Embracing the Now',
    content: "<p>test</p>",
    category: 'Finance',
    categoryId: 1,
    image: "https://picsum.photos/1200/700?random=8",
    isPublished: true,
    isFeatured: true,
  },
  {
    id: 9,
    title: 'Importance of Tourism',
    slug: 'importance-of-tourism',
    authorId: '1afa5662-132d-48d2-8768-9543a4a96501',
    readingTime: 8,
    excerpt: 'Beyond Postcards: Why Tourism Matters More Than You Think',
    content: "<p>test</p>",
    category: 'Lifestyle',
    categoryId: 5,
    image: "https://picsum.photos/1200/700?random=9",
    isPublished: true,
    isFeatured: true,
  },
  {
    id: 10,
    title: 'AI best practices in healthcare',
    authorId: '1afa5662-132d-48d2-8768-9543a4a96501',
    readingTime: 12,
    slug: 'ai-best-practices-in-healthcare',
    excerpt:
      'AI Best Practices in Healthcare: Navigating the Future Responsibly',
    content: "<p>test</p>",
    category: 'Lifestyle',
    categoryId: 7,
    image: "https://picsum.photos/1200/700?random=10",
    isPublished: false,
    isFeatured: false,
  },
];